---
collections:
  - name: containers.podman
    source: https://galaxy.ansible.com
  - name: community.kubernetes
    source: https://galaxy.ansible.com
    version: ">=1.2.0,<2.0.0"
  - name: community.aws
    source: https://galaxy.ansible.com