---
namespace: rsoliman
name: aws_demos
version: 1.0.0
readme: README.md
authors:
  - Raed Soliman <raedrizk@gmail.com>

description: A collection of roles used to demo AWS automation using Ansible.

license:
  - MIT

tags: [AWS, Amazon, demo, ansible, raedrizk, rsoliman]
dependencies:
  amazon.aws: "*"
  ansible.builtin: "*"

repository: http://example.com/repository
homepage: http://example.com
issues: http://example.com/issue/tracker
