---
# tasks file for aws_create_eni
- name: Setting Instance ID
  ansible.builtin.set_fact:
    instance_id: "{{ stat_created_ec2.instances[0].instance_id }}"
  when: stat_created_ec2 is defined and (stat_created_ec2.instances | length) > 0

- name: Setting Instance ID
  ansible.builtin.set_fact:
    instance_id: "{{ stat_created_ec2.tagged_instances[0].instance_id }}"
  when: instance_id is not defined and stat_created_ec2 is defined and (stat_created_ec2.tagged_instances | length) > 0

- name: Create subnet for Infoblox for  vpc
  amazon.aws.ec2_vpc_subnet:
    region: "{{ aws_region }}"
    az: "{{ subnet_az }}"
    vpc_id: "{{ stat_created_vpc_id }}"
    cidr: "{{ cidr_block }}"
    map_public: true
    wait_timeout: 600
    resource_tags:
      Name: "{{ subnet_name_tag }}"
      Provisioner: "{{ provisioner_tag }}"
      Created: "{{ created_tag }}"
  register: create_subnet
  until: create_subnet is not failed
  retries: 15


- name: Create First Additional ENI for the EC2 instance with Infloblox provided IP
  amazon.aws.ec2_eni:
    name: "{{ eni_name }}-1"
    region: "{{ aws_region }}"
    subnet_id: "{{ create_subnet.subnet.id }}"
    security_groups: "{{ ec2_security_group }}"
    description: "{{ eni_description }}"
    delete_on_termination: true
    instance_id: "{{ instance_id }}"
    private_ip_address: "{{ nios_next_ip_address }}"
    device_index: 1
    state: present
    attached: true
    tags:
      Name: "{{ eni_name }}-1"
      Provisioner: "{{ provisioner_tag }}"
      Created: "{{ created_tag }}"
  when: instance_id is defined


