---
# vars file for aws-create-sg
aws_region: "{{ aws_region_choice | default('us-east-1') }}"
provisioner_tag: "{{ provisioner_tag_choice | default('Ansible') }}"
created_tag: "{{ created_tag_choice | default(ansible_date_time.date) }}"

# SG variables 
sg_name_tag: "{{ sg_name_tag_choice | default('Ansible_created_SG') }}"
tcp_ingress_ports:
  - 22
  - 5985
  - 5986
  - 443
  - 80
  - 8080
  