---
# vars file for aws_create_internet_gateway
aws_region: "{{ aws_region_choice | default('us-east-1') }}"
provisioner_tag: "{{ provisioner_tag_choice | default('Ansible') }}"
created_tag: "{{ created_tag_choice | default(ansible_date_time.date) }}"

#subnet Variables
igw_name_tag: "{{ vpc_name_tag_choice | default('Ansible_created_IGW') }}"
