---
# vars file for aws_create_subnet
aws_region: "{{ aws_region_choice | default('us-east-1') }}"
provisioner_tag: "{{ provisioner_tag_choice | default('Ansible') }}"
created_tag: "{{ created_tag_choice | default(ansible_date_time.date) }}"

#subnet Variables
subnet_name_tag: "{{ vpc_name_tag_choice | default('Ansible_created_Subnet') }}"
subnet_az: "{{aws_region}}a"
cidr_block: "172.17.2.0/28"
