---
# tasks file for aws_create_eni
- name: Setting Instance ID
  ansible.builtin.set_fact:
    instance_id: "{{ stat_created_ec2.instances[0].id }}"
  when: stat_created_ec2 is defined and (stat_created_ec2.instances | length) > 0

- name: Setting Instance ID
  ansible.builtin.set_fact:
    instance_id: "{{ stat_created_ec2.tagged_instances[0].id }}"
  when: instance_id is not defined and stat_created_ec2 is defined and (stat_created_ec2.tagged_instances | length) > 0

- name: Create First Additional ENI for the EC2 instance
  amazon.aws.ec2_eni:
    name: "{{ eni_name }}-1"
    description: "{{ eni_desc }}"
    region: "{{ aws_region }}"
    instance_id: "{{ instance_id }}"
    subnet_id: "{{ ec2_subnet_id }}"
    device_index: 1
    security_groups: "{{ ec2_security_group }}"
    state: present
    attached: true
    tags:
      Name: "{{ eni_name }}-1"
      Provisioner: "{{ provisioner_tag }}"
      Created: "{{ created_tag }}"
  when: instance_id is defined

- name: Create Second Additional ENI for the EC2 instance
  amazon.aws.ec2_eni:
    name: "{{ eni_name }}-2"
    description: "{{ eni_desc }}"
    region: "{{ aws_region }}"
    instance_id: "{{ instance_id }}"
    subnet_id: "{{ ec2_subnet_id }}"
    device_index: 2
    security_groups: "{{ ec2_security_group }}"
    state: present
    attached: true
    tags:
      Name: "{{ eni_name }}-2"
      Provisioner: "{{ provisioner_tag }}"
      Created: "{{ created_tag }}"
  when: instance_id is defined
