---
- name: Create AMI
  amazon.aws.ec2_ami:
    instance_id: "{{ hostvars[inventory_hostname].instance_id }}"
    region: "{{ aws_region }}"
    wait: true
    name: "{{ ami_name_tag }}"
    tags:
      Name: "{{ ami_name_tag }}"
      CreatedBy: "{{ ami_createdby_tag }}"
  register: newami
  delegate_to: localhost

- name: Print Info
  ansible.builtin.debug:
    var: newami
  delegate_to: localhost