---
# tasks file for aws_create_keypair
- name: Create or replace EC2 SSH key pair with the name {{ keypair_name }} using provided keypair_material
  amazon.aws.ec2_key:
    name: "{{ keypair_name }}"
    region: "{{ aws_region }}"
    key_material: "{{ keypair_material }}"
  register: created_key

- name: Setting stats for future tasks
  ansible.builtin.set_stats:
    data:
      stat_created_keypair_name: "{{ created_key.key.name | default('') }}"
  when: created_key.key.name is defined

- name: Setting facts for future tasks
  ansible.builtin.set_fact:
    stat_created_keypair_name: "{{ created_key.key.name | default('') }}"
  when: created_key.key.name is defined
